Add missing semi-c

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -49,7 +49,7 @@ jobs:
             f="${file#$(pwd)}"; \
             f="${f/\//}"; \
             echo "Linting $f"; \
-            if [ ! -x "$f" ]; then echo "Error: $f is not executable!"; exit 1; fi \
+            if [ ! -x "$f" ]; then echo "Error: $f is not executable!"; exit 1; fi; \
             docker run -v "$(pwd)":/mnt:ro --rm -t koalaman/shellcheck:v0.7.0 \
               "$f" || exit 1; \
         done;
